Implementation of `Identity` serivce
uselessgoddess/sok pull request #1
Opened 2024-08-26 17:32 UTC by uselessgoddess

2024-08-29 10:41 UTC, uselessgoddess commented
Add the following later: 
- email confirmation 
- password reset
- 2fa auth
- access policies 
- logging and caching

2024-09-02 12:10 UTC, MefistoSamael requested changes
Each layer of application has to be created as class library(except presentation)

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Models/RefreshToken.cs
move to domain layer

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Models/RefreshToken.cs
place empty lines between methods

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Models/AppUser.cs
move to domain

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Models/Role.cs
move to domain

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Commands/Login.cs
> +    }
separate all validators and DTO's

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Commands/Validation.cs
rename class. Move in root of core

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Handlers/DemoteHandler.cs
> +        await users.RemoveFromRolesAsync(user, req.Roles.Select(r => r.ToString()));
await must be preceeded and followed by blank lines

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Handlers/LoginHandler.cs
> +            throw new UnauthorizedException("invalid username or password");
it is badrequest

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Handlers/RefreshHandler.cs
> +            throw new UnauthorizedException();
use badrequest exception

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Handlers/RegisterHandler.cs
> +        }
1. conditional statements must be followed and preceeded by blank lines

2. Use alreadyExists exception

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/Handlers/RegisterHandler.cs
> +                { new ValidationFailure("Email", "user with the same email already exists") });
use badRequest exception

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Core/QueryHandlers/UsersHandlers.cs
1. separate handlers into different files
2. use more descriptive names for handlers

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Infrastructure/Data/DatabaseCx.cs
use more descriptive name

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Infrastructure/Utils.cs
seed db with HasData method

2024-09-02 12:10 UTC, MefistoSamael commented on Identity/Program.cs
separate services configuration in different files by layers

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Core/Commands/Login.cs
> +    }
but this isn't DTO))

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Core/Handlers/DemoteHandler.cs
> +        await users.RemoveFromRolesAsync(user, req.Roles.Select(r => r.ToString()));
```suggestion
        var user = await users.FindByIdAsync(req.Id) ?? throw new NotFoundException();

        await users.RemoveFromRolesAsync(user, req.Roles.Select(r => r.ToString()));
```

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Core/Handlers/LoginHandler.cs
> +            throw new UnauthorizedException("invalid username or password");
```suggestion
            throw new BadRequestException("invalid username or password");
```

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Core/Handlers/RefreshHandler.cs
> +            throw new UnauthorizedException();
```suggestion
            throw new BadRequestException();
```

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Core/Handlers/RegisterHandler.cs
> +                { new ValidationFailure("Email", "user with the same email already exists") });
```suggestion
            throw new BadRequestException("user with the same email already exists");
```

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Core/QueryHandlers/UsersHandlers.cs
1. ok
2. names are subjective, but their len saves the memory

2024-09-02 12:42 UTC, uselessgoddess commented on Identity/Infrastructure/Data/DatabaseCx.cs
how can I improve descriptive of `Database Context`

2024-09-02 12:57 UTC, uselessgoddess commented on Identity/Infrastructure/Utils.cs
but why? my way is easier and hides low-level representation

2024-09-06 11:28 UTC, MefistoSamael commented on Identity/Core/QueryHandlers/UsersHandlers.cs
you shoudn't care so much about memory in such types of application

2024-09-06 11:29 UTC, MefistoSamael commented on Identity/Core/QueryHandlers/UsersHandlers.cs
at first you should care about maintainability and extendibility

2024-09-06 11:31 UTC, MefistoSamael commented on Identity/Infrastructure/Utils.cs
naming conventions) ¯\_(ツ)_/¯

2024-09-06 11:51 UTC, MefistoSamael requested changes

2024-09-06 11:51 UTC, MefistoSamael commented on Identity/Api/Program.cs
> +});
take it away from program

2024-09-06 11:51 UTC, MefistoSamael commented on Identity/Api/App/Controllers/AccountController.cs
separate business logic from presentation logic

2024-09-18 17:17 UTC, MefistoSamael requested changes

2024-09-18 17:17 UTC, MefistoSamael commented on Identity/Api/Program.cs
> +builder.Services.AddSwaggerGen(c => { c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme()); });
move to api configuration

2024-09-18 17:17 UTC, MefistoSamael commented on Identity/Api/DependencyInjection.cs
> +        return builder;
move to infrastructure configuration

2024-09-18 17:17 UTC, MefistoSamael commented on Identity/UseCases/Services/TokenService.cs
move to infrastructure

2024-09-20 12:57 UTC, MefistoSamael approved these changes

2024-09-20 15:13 UTC, merged